#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

GLOBAL_ENV_FILE="/home/dokku/GLOBAL_ENV

STDIN=$(cat)
output=""
if [ "$2" = "deploy" ]; then
    #TODO: Check apps config before rewrite it
    output="--env-file=$GLOBAL_ENV_FILE"
fi

echo "$STDIN$output